image: node:latest

stages:
  - install
  - lint
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - npm install

lint:
  stage: lint
  script:
    - npm install
    - npx eslint .
    
sast:
  stage: test

build:
  stage: build
  script:
    - npm install
    - npx expo build

deploy:
  stage: deploy
  script:
    - npm install
    - npm install -g expo-cli
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npx expo signin -u ryang_linkpoint -p L1nk@P01nt
    - npx expo publish

include:
- template: Security/SAST.gitlab-ci.yml